version: "3.8"
services:
  app:
    build: .
    container_name: success13
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://success.c9o2muimyf8j.ap-northeast-2.rds.amazonaws.com:3306/success
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - success13-database
    restart: always

  success13-database:
    container_name: success13-database
    image: yujin748/success13-database
    #build:
       #dockerfile: Dockerfile
       #context: ./database
    environment:
      - MYSQL_DATABASE=success13
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./databases/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always
